#!/bin/sh  /etc/rc.common

START=99

USE_PROCD=1

PROG=/usr/bin/gl_fan

get_fan_config() {
    config_get enabled $1 enabled
    config_get temperature $1 temperature
    config_get proportion $1 proportion
    config_get integration $1 integration
    config_get differential $1 differential
    config_get debug $1 debug
}

start_service() {
    config_load glfan
    config_foreach get_fan_config globals

    [ "$enabled" != "1" ] && exit
    [ -n "$temperature" ] && PROG="$PROG -t $temperature"
    [ -n "$proportion" ] && PROG="$PROG -p $proportion"
    [ -n "$integration" ] && PROG="$PROG -i $integration"
    [ -n "$differential" ] && PROG="$PROG -d $differential"
    [ "$debug" = "1" ] && PROG="$PROG -v"

    procd_open_instance
    procd_set_param respawn
    procd_set_param stderr 1
    procd_set_param command $PROG
    procd_close_instance
}

stop_service() {
    kill -9 $(pgrep -f '/usr/bin/gl_fan') 2>/dev/null
    echo 0 > /sys/class/thermal/cooling_device0/cur_state
}